specVersion: 1.0.0
name: concordium-indexer-onfinality
version: 0.1.0
description: Index Concordium account transfers and updated events. Deployable on OnFinality.
runner:
  node:
    name: '@subql/node-concordium'
    version: '>=2.0.0'
  query:
    name: '@subql/query'
    version: '>=2.0.0'
schema:
  file: ./schema.graphql

network:
  # OnFinality will provide the network endpoint at deployment time.
  # You may set a local endpoint for development if you wish:
  # endpoint:
  #   - 'https://grpc.testnet.concordium.com:20000'
  # Genesis block hash for Concordium testnet (used by OnFinality to validate the RPC endpoint)
  chainId: '4221332d34e1694168c2a0c0b3fd0f273809612cb13d000d5c2e00e85f50f796'
  endpoint:
    - 'https://grpc.testnet.concordium.com:20000'
dataSources:
  - kind: concordium/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleAccountTransfer
          kind: concordium/TransactionHandler
          filter:
            type: accountTransaction
            values:
              transactionType: transfer
        - handler: handleUpdatedEvent
          kind: concordium/TransactionEventHandler
          filter:
            type: Updated
# ci: trigger workflow re-run
# ci: re-run after adding SUBQL_ACCESS_TOKEN
