specVersion: 1.0.0
name: concordium-indexer-onfinality
version: 0.1.0
description: Index Concordium account transfers and updated events. Deployable on OnFinality.
runner:
  node:
    name: '@subql/node-concordium'
    version: '>=2.0.0'
  query:
    name: '@subql/query'
    version: '>=2.0.0'
schema:
  file: ./schema.graphql

network:
  # OnFinality will provide the network endpoint at deployment time.
  # You may set a local endpoint for development if you wish:
  # endpoint:
  #   - 'https://grpc.mainnet.concordium.com:20000'
  # Genesis block hash for Concordium mainnet (used by OnFinality to validate the RPC endpoint)
  chainId: '9dd9ca4d19e9393877d2c44b70f89acbfc0883c2243e5eeaecc0d1cd0503f478'
dataSources:
  - kind: concordium/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleAccountTransfer
          kind: concordium/TransactionHandler
          filter:
            type: accountTransaction
            values:
              transactionType: transfer
        - handler: handleUpdatedEvent
          kind: concordium/TransactionEventHandler
          filter:
            type: Updated
# ci: trigger workflow re-run
# ci: re-run after adding SUBQL_ACCESS_TOKEN
