specVersion: 1.0.0
name: concordium-indexer-onfinality
version: 0.1.0
description: Index Concordium account transfers and updated events. Deployable on OnFinality.
runner:
  node:
    name: '@subql/node-concordium'
    version: '>=2.0.0'
  query:
    name: '@subql/query'
    version: '>=2.0.0'
schema:
  file: ./schema.graphql
network:
  # OnFinality will provide the network endpoint at deployment time.
  # You may set a local endpoint for development if you wish:
  # endpoint:
  #   - 'grpc.testnet.concordium.com:20000'
  endpoint: []
dataSources:
  - kind: concordium/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleAccountTransfer
          kind: concordium/Transaction
          filter:
            type: AccountTransaction
            values:
              transactionType: transfer
        - handler: handleUpdatedEvent
          kind: concordium/TransactionEvent
          filter:
            type: Updated
# ci: trigger workflow re-run